# version: "3"
# services:
  app:
    container_name: app_$BUILD_NUMBER
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    links:
      - mongo
  client:
    container_name: client_$BUILD_NUMBER
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
  mongo:
    container_name: mongo_$BUILD_NUMBER
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
